# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/c/fastj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/c/fastj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/c/fastj/CMakeFiles /root/c/fastj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/c/fastj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fastj

# Build rule for target.
fastj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fastj
.PHONY : fastj

# fast build rule for target.
fastj/fast:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/build
.PHONY : fastj/fast

fastj.o: fastj.c.o
.PHONY : fastj.o

# target to build an object file
fastj.c.o:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/fastj.c.o
.PHONY : fastj.c.o

fastj.i: fastj.c.i
.PHONY : fastj.i

# target to preprocess a source file
fastj.c.i:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/fastj.c.i
.PHONY : fastj.c.i

fastj.s: fastj.c.s
.PHONY : fastj.s

# target to generate assembly for a file
fastj.c.s:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/fastj.c.s
.PHONY : fastj.c.s

hash.o: hash.c.o
.PHONY : hash.o

# target to build an object file
hash.c.o:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/hash.c.o
.PHONY : hash.c.o

hash.i: hash.c.i
.PHONY : hash.i

# target to preprocess a source file
hash.c.i:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/hash.c.i
.PHONY : hash.c.i

hash.s: hash.c.s
.PHONY : hash.s

# target to generate assembly for a file
hash.c.s:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/hash.c.s
.PHONY : hash.c.s

picohttpparser.o: picohttpparser.c.o
.PHONY : picohttpparser.o

# target to build an object file
picohttpparser.c.o:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/picohttpparser.c.o
.PHONY : picohttpparser.c.o

picohttpparser.i: picohttpparser.c.i
.PHONY : picohttpparser.i

# target to preprocess a source file
picohttpparser.c.i:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/picohttpparser.c.i
.PHONY : picohttpparser.c.i

picohttpparser.s: picohttpparser.c.s
.PHONY : picohttpparser.s

# target to generate assembly for a file
picohttpparser.c.s:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/picohttpparser.c.s
.PHONY : picohttpparser.c.s

slog.o: slog.c.o
.PHONY : slog.o

# target to build an object file
slog.c.o:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/slog.c.o
.PHONY : slog.c.o

slog.i: slog.c.i
.PHONY : slog.i

# target to preprocess a source file
slog.c.i:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/slog.c.i
.PHONY : slog.c.i

slog.s: slog.c.s
.PHONY : slog.s

# target to generate assembly for a file
slog.c.s:
	$(MAKE) -f CMakeFiles/fastj.dir/build.make CMakeFiles/fastj.dir/slog.c.s
.PHONY : slog.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fastj"
	@echo "... rebuild_cache"
	@echo "... fastj.o"
	@echo "... fastj.i"
	@echo "... fastj.s"
	@echo "... hash.o"
	@echo "... hash.i"
	@echo "... hash.s"
	@echo "... picohttpparser.o"
	@echo "... picohttpparser.i"
	@echo "... picohttpparser.s"
	@echo "... slog.o"
	@echo "... slog.i"
	@echo "... slog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

